image: bradrydzewski/go:1.2
script:
  - go version
  - go get -t ./...
  - go build ./...
  - go test -race -short ./...
  - go vet -x ./...
notify:
  email:
    recipients:
      - charlie.knudsen@gmail.com
